test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.subdir", "install.multi", "change_url"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.server = "vanilla"
	args.ram = "1024"
	args.op = "johndoe"