test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.server = "vanilla"
	args.ram = "1024"
	args.op = "johndoe"