#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

gamemode=survival
level_seed=""
max_players=20
motd="A Minecraft Server"
password=$YNH_APP_ARG_PASSWORD

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set --app=$app --key=ram --value=$ram
ynh_app_setting_set --app=$app --key=gamemode --value=$gamemode
ynh_app_setting_set --app=$app --key=level_seed --value=$level_seed
ynh_app_setting_set --app=$app --key=max_players --value=$max_players
ynh_app_setting_set --app=$app --key=motd --value=$motd
ynh_app_setting_set --app=$app --key=password --value=$password

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=10

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" --source_id="$server"

mkdir -p "$install_dir/mcrcon"
ynh_setup_source --dest_dir="$install_dir/mcrcon" --source_id="mcrcon"	

chmod 755 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"
chmod +x "$install_dir/mcrcon/mcrcon"
chmod +x "$install_dir/server.jar"

#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_script_progression --message="Configuring configuration files..." --weight=2

ynh_add_config --template="../conf/server.properties" --destination="$install_dir/server.properties"
ynh_add_config --template="../conf/ops.txt" --destination="$install_dir/ops.txt"
ynh_add_config --template="../conf/eula.txt" --destination="$install_dir/eula.txt"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Configuring a systemd service..." --weight=2

# Create a dedicated systemd config
ynh_add_systemd_config

yunohost service add $app --description="Three-dimensional sandbox construction game" --log="/var/log/$app/$app.log" --needs_exposed_ports="$port"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=3

ynh_systemd_action --service_name=$app --action=start --log_path=systemd --line_match="RCON running on"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
