#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_clean_setup () {
	true
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

# Retrieve arguments
server=$YNH_APP_ARG_SERVER
ram=$YNH_APP_ARG_RAM
op=$YNH_APP_ARG_OP
rcon=$YNH_APP_ARG_RCON
password=$YNH_APP_ARG_PASSWORD
eula=$YNH_APP_ARG_EULA

app=$YNH_APP_INSTANCE_NAME

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================
ynh_script_progression --message="Validating installation parameters..." --weight=1

final_path=/home/yunohost.app/$app
test ! -e "$final_path" || ynh_die --message="This path already contains a folder"

if [ "$eula" != "true" ]
then
	ynh_die --message="You must accept the EULA in order to install the app" --ret_code=1
fi

#=================================================
# FIND AND OPEN A PORT
#=================================================
ynh_script_progression --message="Finding an available port..." --weight=2

# Find a free port
port=$(ynh_find_port --port=25565)
ynh_app_setting_set --app=$app --key=port --value=$port

# Open this port
ynh_exec_warn_less yunohost firewall allow --no-upnp TCP $port

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing dependencies..." --weight=5

ynh_install_app_dependencies $pkg_dependencies

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=10

ynh_app_setting_set --app=$app --key=final_path --value=$final_path
# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$final_path" --source_id="$server"

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_script_progression --message="Configuring system user..." --weight=1

# Create a system user
ynh_system_user_create --username=$app

#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_add_config --template="../conf/server.properties" --destination="$final_path/server.properties"
# ynh_replace_string --match_string="__PORT__" --replace_string="$port" --target_file="../conf/server.properties"
# ynh_replace_string --match_string="__RCON__" --replace_string="$rcon" --target_file="../conf/server.properties"
# ynh_replace_string --match_string="__PASSWORD__" --replace_string="$password" --target_file="../conf/server.properties"
# cp -a ../conf/server.properties $final_path/server.properties

ynh_add_config --template="../conf/ops.txt" --destination="$final_path/ops.txt"
# ynh_replace_string --match_string="__OP__" --replace_string="$op" --target_file="../conf/ops.txt"
# cp -a ../conf/ops.txt $final_path/ops.txt

ynh_add_config --template="../conf/eula.txt" --destination="$final_path/eula.txt"
# ynh_replace_string --match_string="__EULA__" --replace_string="$eula" --target_file="../conf/eula.txt"
# cp -a ../conf/eula.txt $final_path/eula.txt

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Configuring a systemd service..." --weight=2

ynh_replace_string "__RAM__" "$ram" "../conf/systemd.service"
ynh_replace_string "__FINALPATH__" "$final_path" "../conf/systemd.service"

# Create a dedicated systemd config
ynh_add_systemd_config

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..." --weight=1

yunohost service add $app --description="Three-dimensional sandbox construction game" --log="/var/log/$app/$app.log"

#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

chown -R $app: $final_path
chmod -R 755 $final_path

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=3

ynh_systemd_action --service_name=$app --action=start --log_path=systemd --line_match="RCON running on"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
