#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

if yunohost service status $app >/dev/null 2>&1
then
	ynh_script_progression --message="Removing $app service"
	yunohost service remove $app
fi

# Remove the dedicated systemd config
ynh_remove_systemd_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed"
