#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

password=$(ynh_app_setting_get --key=password)

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# If install_dir doesn't exist, create it
#if [ -z "${install_dir/mcrcon:-}" ]; then
#	mkdir -p $install_dir/mcrcon
#fi

# If ram doesn't exist, create it
ynh_app_setting_set_default --key=ram --value=1024

# If server doesn't exist, create it
ynh_app_setting_set_default --key=server --value=vanilla

# If gamemode doesn't exist, create it
ynh_app_setting_set_default --key=gamemode --value=survival

# If level_seed doesn't exist, create it
ynh_app_setting_set_default --key=level_seed --value=""

# If max_players doesn't exist, create it
ynh_app_setting_set_default --key=max_players --value=20

# If motd doesn't exist, create it
ynh_app_setting_set_default --key=motd --value="A Minecraft Server"

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action=stop --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --source_id="$server" --keep="ops.txt eula.txt server.properties"

ynh_setup_source --dest_dir="$install_dir/mcrcon" --source_id="mcrcon"

chmod +x "$install_dir/mcrcon/mcrcon"
chmod +x "$install_dir/server.jar"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Upgrading systemd configuration..."

ynh_config_add_systemd

yunohost service add $app --description="Three-dimensional sandbox construction game" --log="/var/log/$app/$app.log" --needs_exposed_ports="$port"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action=start --log_path=systemd --wait_until="RCON running on"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
