#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..."

# If install_dir doesn't exist, create it
if [ -z "${install_dir/mcrcon:-}" ]; then
	mkdir -p $install_dir/mcrcon
fi

# If ram doesn't exist, create it
if [ -z "${ram:-}" ]; then
	ram="1024"
	ynh_app_setting_set --app=$app --key=ram --value=$ram
fi

# If server doesn't exist, create it
if [ -z "${server:-}" ]; then
	server=vanilla
	ynh_app_setting_set --app=$app --key=vanilla --value=$vanilla
fi

# If gamemode doesn't exist, create it
if [ -z "${gamemode:-}" ]; then
	gamemode=survival
	ynh_app_setting_set --app=$app --key=survival --value=$survival
fi

# If level_seed doesn't exist, create it
if [ -z "${level_seed:-}" ]; then
	level_seed=""
	ynh_app_setting_set --app=$app --key=level_seed --value=$level_seed
fi

# If max_players doesn't exist, create it
if [ -z "${max_players:-}" ]; then
	max_players=20
	ynh_app_setting_set --app=$app --key=max_players --value=$max_players
fi

# If motd doesn't exist, create it
if [ -z "${motd:-}" ]; then
	motd="A Minecraft Server"
	ynh_app_setting_set --app=$app --key=motd --value=$motd
fi

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..."

ynh_systemd_action --service_name=$app --action=stop --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading source files..."

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir" --source_id="$server" --keep="ops.txt eula.txt"

	ynh_setup_source --dest_dir="$install_dir/mcrcon" --source_id="mcrcon"	
fi

# Set permissions to app files
chmod 755 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"
chmod +x "$install_dir/mcrcon/mcrcon"
chmod +x "$install_dir/server.jar"

#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_script_progression --message="Updating the configuration file..." --weight=1

ynh_add_config --template="../conf/server.properties" --destination="$install_dir/server.properties"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Upgrading systemd configuration..."

# Create a dedicated systemd config
ynh_add_systemd_config

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..."

yunohost service add $app --description="Three-dimensional sandbox construction game" --log="/var/log/$app/$app.log" --needs_exposed_ports="$port"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..."

ynh_systemd_action --service_name=$app --action=start --log_path=systemd --line_match="RCON running on"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
